### ISSUE TITLE
Markdown export

### ISSUE THREAD

**Issue by mgottholsen** [yogthos/mastodon-bot#12]
Would it be possible to add support for exporting or saving syndicated content into a Markdown file? Similar in operation to how belong.io or latest.is works (harvests urls from specific users on Twitter, generates a webpage of links), this could be integrated in a static site generator publishing process such as Jekyll or Hugo.

**Comment by yogthos** [comment]
It should be fairly straight forward to do, but I think it might be better to create a separate project for this.

**Comment by yogthos** [comment]
I'll close the issue, but [here's](https://gist.github.com/yogthos/d8745f75fc930d5b255193f94e82d6f4) an example script that will write Tweets to Markdown from a given account.
