### ISSUE TITLE
missing Mastodon client configuration!

### ISSUE THREAD

**Issue by lordkitsuna** [yogthos/mastodon-bot#15]
Not sure whats going on with this one, when i go to run the script it just exits with that error. I have that area of the config file filled out fully.

**Comment by lordkitsuna** [comment]
When i was commenting out twitter i accidentally caught the first bracket as well. now the script runs and doesn't show any error but its also not posting anything from Tumblr as i setup. any way to get a more verbose output and figure out what might be going on on that front?

**Comment by lordkitsuna** [comment]
Just to be sure it was doing anything i at least did some snooping with tcpdump. I can see the bot call out to the tumblr pages ive setup so its at least trying. Cant figure out why its not actually posting anything to the mastodon instance though. 

EDIT: i went ahead and uncommented the default RSS settings and those posted just fine so for some reason its only tumblr that is not pulling in posts any idea what could cause no errors but still not get anything?

**Comment by yogthos** [comment]
Hmm, I'll have to take a look. I haven't been using Tumblr functionality myself so maybe the API changed since I added it in.

**Comment by lordkitsuna** [comment]
Hey thanks for the quick reply, Starting to think its just something else about my setup. Twitter api got approved and that does not appear to be working either i randomly got it to finally post a single post from one of the tumblrs and then never again. only the RSS seems to work and i cant figure out why. Here is my config for reference

```{;; add Twitter config to mirror Twitter accounts
 :twitter {:access-keys
           {:consumer_key "keyhere"
            :consumer_secret "keyhere"
            :access_token_key "keyhere"
            :access_token_secret "keyhere"}
           ;; optional, defaults to false
           :include-replies? false
           ;; optional, defaults to false
           :include-rts? false
           ;; accounts you wish to mirror
           :accounts ["zedrinbot"]}
;;  add Tumblr config to mirror Tumblr accounts
 :tumblr {:access-keys
          {:consumer_key "keyhere"
           :consumer_secret "keyhere"
           :token "keyhere"
           :token_secret "keyhere"}
          ;; optional limit for number of posts to retrieve, default: 5
          :limit 1000
          :accounts ["cyberpunky.tumblr.com" "scipunk.tumblr.com"]}
;; add RSS config to follow feeds
 :rss {"Hacker News" "https://hnrss.org/newest"
      "r/Clojure" "https://www.reddit.com/r/clojure/.rss"}
 :mastodon {:access_token "keyhere"
            :api_url "https://art.kitsuna.net/api/v1/"
            ;; optional boolean to mark content as sensitive
            :sensitive true
            ;; optional visibility flag: direct, private, unlisted, public
            ;; defaults to unlisted
            :visibility "public"
            ;; optional limit for the post length
            :max-post-length 300
            ;; optional flag specifying wether the name of the account
            ;; will be appended in the post, defaults to false
            :append-screen-name? false
            ;; optional signature for posts
            :signature "#mediabot"
            ;; optionally try to resolve URLs in posts to skip URL shorteners
            ;; defaults to false
            :resolve-urls? true
            ;; optional content filter regexes
            ;; any posts matching the regexes will be filtered out
            ;; :content-filters ["."]
            ;; optional keyword filter regexes
            ;; any posts not matching the regexes will be filtered out
            ;; :keyword-filters []
}}```

**Comment by yogthos** [comment]
Oh, I think I know what might be happening here. The bot checks the timestamp on the last post from Mastodon, and then only posts things that are after that to avoid reposting old content. In case there aren't any posts, the time defaults to now. So, any older Tumbler/Twitter posts will get filtered out by that.

**Comment by lordkitsuna** [comment]
Perfect! that appears to have been it didn't realize it wouldn't back pull but it makes sense now that i think about it. Maybe just mention it in the readme to avoid more people like me :P Thanks for the help

**Comment by yogthos** [comment]
Good idea, I'll add a note as it's not really obvious in retrospect. :)
