### ISSUE TITLE
Fails silently for Pleroma accounts

### ISSUE THREAD

**Issue by JosephKiranBabu** [yogthos/mastodon-bot#22]
I was successfully running a news bot on a Mastodon instance using mastodon-bot. However, when I follow the same instructions for a Pleroma instance, the bot fails silently with no errors. 

I have added multiple RSS feeds to the bot's config.edn, but no posts are made.

The OAuth token is not shown in the Security tab of the Pleroma user settings, but there are CSP errors and blocked inline JS, so I'm not sure about that. I was able to get to the last step of the instructions successfully and obtained an access token which I entered into config.edn

**Comment by yogthos** [comment]
Hi,

I haven't tried using the bot with Pleroma myself, and I'm guessing there are probably some differences in the API. First thing to look at would be whether [mastodon-api](https://www.npmjs.com/package/mastodon-api) NPM module is compatible.

**Comment by jerger** [comment]
We've improved rss-feeds exception handling - the rss problem may have been gone :-)
Therefore I close this issue, pls reopen if rss problem persists.

Reg. Pleroma I've no idea ... I don't use it ...

If you want to trace this down, I can offer my assistance in debugging this issue ...
