### ISSUE TITLE
action is outside the authorized scopes

### ISSUE THREAD

**Issue by jerger** [yogthos/mastodon-bot#24]
It tried the mastodon-bot with twitter & my mastodon server (ver. 2.9.2) and get these message:

```
root@6b3c928e7c96:/app/mastodon-bot# ./mastodon-bot.cljs
This action is outside the authorized scopes
```
Unsure whether this message comes from twitter or mastodon ... but google search seems to know this message as mastodon client issue - correct?

I reviewed all my api keys, the mastodon api url is working e.g. for `https://social.meissa-gmbh.de/api/v1/accounts/1`.

The mastodon app has the permissions to `read* write* follow push`  ... any idea what could be wrong?

**Comment by yogthos** [comment]
Hmm, it does seem like the problem is on Mastodon side, but not sure what's causing that specifically.

**Comment by jerger** [comment]
Found similar for mastodon.el: https://github.com/jdenen/mastodon.el/issues/1

But I estimate, your using https://github.com/vanita5/mastodon-api ;-)

**Comment by yogthos** [comment]
Yeah that's the one, so I guess the client needs to be updated upstream then. I haven't had a chance to look, but might be easy enough to call the API directly using the request module. I think the client just constructs the request using the token.

**Comment by jerger** [comment]
I will try to solve the issue, but I will need some time to get into cljs & js. I try to explore your code by getting dirty hands - what do you think about starting with a refactoring
(separate mastodon / rss / thumbler / twitter in namespaces & define the input / output using spec) ?

First steps I tried here: https://github.com/DomainDrivenArchitecture/mastodon-bot/blob/refactoring/mastodon_bot/mastodon_api.cljs

Do you like the idea or should I handle my learning-journey just as some kind of coding-kata?

**Comment by yogthos** [comment]
Splitting things up sounds good to me, and definitely not opposed to having some specs around things. A PR is very welcome if you get it all working the way you like. :)

**Comment by jerger** [comment]
Can no longer reproduce this issue.
