### ISSUE TITLE
Reverse order of tweets posted

### ISSUE THREAD

**Issue by marians** [yogthos/mastodon-bot#27]
Thanks for mastodon-bot!

I noticed that when posting multiple tweets to Mastodon, the most recent tweet is posted first and the oldest is posted last, resulting in a reverse ordering.

How little work would it be to reverse the ordering of the twitter feed before processing it?

Unfortunately I have zero insights in Clojure development, so I am not able to solve this issue on my own.

**Comment by yogthos** [comment]
Ah, I think it should just be a matter of doing reverse in the [post-itmes](https://github.com/yogthos/mastodon-bot/blob/d79b9fa5c31c99f39468869ee366f01d449ea7bc/mastodon-bot.cljs#L131) function:

```clojure
(defn post-items [last-post-time items]
  (doseq [{:keys [text media-links]} (->> items
                                          (remove #(blocked-content? (:text %)))
                                          (filter #(> (:created-at %) last-post-time))
                                          (reverse))] ;; reverse the items
    (if media-links
      (post-status-with-images text media-links)
      (when-not (:media-only? mastodon-config)
        (post-status text)))))
```
Let me know if that does the trick.

**Comment by marians** [comment]
Thanks! I'll try that on the next occasion and if it works, I'll send a PR.

**Comment by yogthos** [comment]
👍

**Comment by marians** [comment]
Dev question: How do I update the compiled `mastodon-bot.js` file?

**Comment by yogthos** [comment]
Ah, I haven't checked that part in. You have to run the ClojureScript compiler for that, I'll that part in. I use the cljs version myself via Lumo.
