### ISSUE TITLE
Publish to npmjs.org

### ISSUE THREAD

**Issue by raboof** [yogthos/mastodon-bot#39]
I'd like to have mastodon-bot published to npmjs.org (because that makes it much easier to get it packaged for Nix).

I can take have a look at settings things up. Would that be OK with you, or would you prefer not to?

**Comment by yogthos** [comment]
Yeah that sounds great. [This](https://andrearichiardi.com/blog/posts/lumo-npm-dependencies.html) might be helpful for getting things published to NPM.

**Comment by raboof** [comment]
This now works (though it's a manual action)
