### ISSUE TITLE
‘lumo’: No such file or directory

### ISSUE THREAD

**Issue by nvjacobo** [yogthos/mastodon-bot#4]
$ ./mastodon-bot.cljs
/usr/bin/env: ‘lumo’: No such file or directory

$ node -v
v9.11.1
$npm -v
5.6.0

**Comment by yogthos** [comment]
The script looks for [Lumo](https://github.com/anmonteiro/lumo) on the path, you'd have to install is globally to run the script standalone:

    npm install -g lumo-cljs

If you get a permission failure, try this:

    npm install -g lumo-cljs --unsafe-perm

**Comment by nvjacobo** [comment]
Thanks

$ npm install -g lumo-cljs --unsafe-perm
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
npm ERR! path /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!  { Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mastodon/.npm/_logs/2018-05-10T22_45_21_800Z-debug.log

**Comment by yogthos** [comment]
looks like  you might  have  to install with `sudo` as npm doesn't appear to have permission to write to your `/user/lib/node_modules`  folder.

**Comment by nvjacobo** [comment]
Thanks, 

Fixed :)
