### ISSUE TITLE
More differentiated transformation

### ISSUE THREAD

**Issue by jerger** [yogthos/mastodon-bot#45]
I've about 20 twitter accounts I follow. I would like to read them on mastodon. But some are technical and some are more political. So it would be cool, to use different signatures / keyword-filters / twitter-reply settings for groups of accounts.

I can imagine two options to achieve this:
1. I can create several configs and run the bot for each config. In this case it would be cool, if config filename can be handed over as cli parameter.
2. refactor configuration to separate api-authorization from transformation configurations (we could have a sequence of transformations (e.g. some rss->mastodon, twitter(having tech.-accounts) -> mastodon) od twitter(having political accounts) -> mastodon)

Layout could be sth like

```
{:twitter-auth { ... all the keys ...}
 :masto-auth {:access_token "XXXX"
                      :account-id "XXXX"
                      :api_url "https://botsin.space/api/v1/"}
 :transformations [
   {:source-rss {"Hacker News" "https://hnrss.org/newest"}
    :target-masto {:signature "#rssbot"
                           :resolve-urls? true
                           :keyword-filters [".*clojure.*"]}}
   {:source-twitter {:include-replies? false
                             :accounts ["WIRED"]}
    :target-masto {:signature "#twitterwiredbot"
                           :resolve-urls? true
                           :keyword-filters [".*clojure.*"]}}
 ]
}
```

What do you think about ?

**Comment by yogthos** [comment]
That seems like it could be reasonable, another option could be to add the transform rules under the config map for each service, e.g:

```clojure
{:twitter
  {:access-keys ...
   :transform
   [{:accounts ["WIRED"] :include-replies? false :signature "#twitterbot"} ...]}
```

**Comment by jerger** [comment]
Let's call your idea no 3.

idea no 3 would have the charm, that the source credentials are very clear assigned. And I like the impression `:signature` binds stronger to the source. But on the other hand in combination with #46 the used target credentials are very implicit and we can not express mastodon->twitter.

What do you think about a combination of idea no 2 & no 3?
As I'm quite a fan of [aero](https://github.com/juxt/aero) we could use aero's references. 
In this case config can look like:

```
{:auth {:twitter { ... credentials ...}
            :mastodon { ... credentials ... }}
 :transform [
  {:source #ref [:auth :twitter] :target #ref [:auth :mastodon]
   :accounts ["WIRED"] :include-replies? false :signature "#twitterbot"} ...]}
```

Advantages would be:
1. we can reuse the auth-config-parts wherever we will need em.
2. direction is expressive
3. transform will become a first class citizen (namespace). And we can e.g. think about whether signature is part of transformation vs. part of mastodon-api vs. part of twitter-api.
4. we can even have more than only one credential per api - in case #46 the source mastodon account will not be the bot-account. I'm not sure, whether mastodons public timeline access will be enough.
5. It is in general a good practice to separate credentials from rest of configuration (in devops we depend heavily on git managed configuration - without exposing the credential part). We are using aroe's `include` in this scenario. But let's handle this argument only as a weak feeling, as I think that is not really relevant in our case.

**Comment by yogthos** [comment]
I'm ok with the idea of decoupling the transform from the account config to facilitate having different sources. It would probably be sufficient to specify the type of source e,.g: `{:source :twitter ...}` since the path is just an implementation detail. Pulling in aero for this might be a bit ovekill. :)

**Comment by jerger** [comment]
done :-)

**Comment by yogthos** [comment]
🎉
