### ISSUE TITLE
README needs updating

### ISSUE THREAD

**Issue by raboof** [yogthos/mastodon-bot#49]
I'm a bit confused how to build/run the project after #43 and #44: neither `npm start`/`npm test` nor `npx shadow-cljs release app` seem to work anymore.

**Comment by yogthos** [comment]
there's a big update by @jerger coming https://github.com/yogthos/mastodon-bot/pull/48 and that will fix the start issue, and also make it easier to set up overall going directly through npm

**Comment by raboof** [comment]
Publishing the compiled sources to npmjs would definitely make things easier downstream!

For development, on that branch `npx shadow-cljs release app` indeed works again, though `npx shadow-cljs test` just shows `TBD`.

**Comment by Manav16** [comment]
@yogthos I'm using the updated version from @jerger, and I too am able to now compile using `shadow-cljs release app`. All I do is edit test.edn with the details, and create config.edn. 

but after that, once I run it using `node target/mastodon-bot.js` or `node target/mastodon-bot.js config.edn` It doesn't mirror tweets. It instead uses the source-type rss. The output in the terminal I get when running is just
```
https://hnrss.org/newest
https://www.reddit.com/r/clojure/.rss
```

and output on the mastodon account is 

```
...
#
#rssbot
```

Although I kept the source as twitter and target as mastodon. I have entered all the config details for Twitter and Mastodon, and it is able to post to the concerned Mastodon account. I feel like i'm just doing some small mistake or haven't caught onto something. Would you have an idea on what i'm doing wrong? Thank you, especially for all the great work you two are doing.

**Comment by jerger** [comment]
can u provide the transformation config to me ?
If all of your sources are public, I can have a look on it :-)

**Comment by Manav16** [comment]
> can u provide the transformation config to me ?
> If all of your sources are public, I can have a look on it :-)

https://pastebin.com/j2PMe04H - Copy pasted from the config file. Thank you for taking out the time!

**Comment by jerger** [comment]
> Publishing the compiled sources to npmjs would definitely make things easier downstream!
> 
> For development, on that branch `npx shadow-cljs release app` indeed works again, though `npx shadow-cljs test` just shows `TBD`.

I use `shadow-cljs watch test` for testing. Will remove the test section from package.json in order to reduce confusion :-)

**Comment by raboof** [comment]
> I use `shadow-cljs watch test` for testing

Thanks, that seems to work (though all my tests in `core_test.cljs` are commented out so I guess I have some work to do before I can resume contributing again :smile: )

**Comment by jerger** [comment]
jupp, sorry for not continuing these tests. Did a major refactoring found no smart way to keep them running.
If your eager to contribute, I can provide contribution access to you on may fork :-)

**Comment by raboof** [comment]
> If your eager to contribute, I can provide contribution access to you on may fork :-)

I can PR to your fork :). Though if you didn't see a way to test those features in isolation after your refactoring I'm not sure I would have a better chance...

**Comment by jerger** [comment]
@raboof lets move this discussion to #45 ?

**Comment by jerger** [comment]
> > can u provide the transformation config to me ?
> > If all of your sources are public, I can have a look on it :-)
> 
> https://pastebin.com/j2PMe04H - Copy pasted from the config file. Thank you for taking out the time!

@Manav16 can reproduce your issue & will work on it

**Comment by jerger** [comment]
@Manav16 found first issue (https://github.com/yogthos/mastodon-bot/pull/48/commits/dbc5f8cd25c0b1820cbdb275ee274e817cb79771)
& have to fix a second one (default-values are not set).

In meantime, if you take the newest mastodon-bot,js & add `:max-post-length` to your target config. In your example this could be:

```
:transform [{:source {:source-type :rss
            ;; add RSS config to follow feeds
                       :feeds [["Hacker News" "https://hnrss.org/newest"]
                               ["r/Clojure" "https://www.reddit.com/r/clojure/.rss"]]}
              :target {:target-type :mastodon
                       :append-screen-name? false
                       :max-post-length 500
                       :signature "#rssbot"}
              :resolve-urls? false
              :content-filters [".*bannedsite.*"]
              :replacements nil}         
             ]
```

rss is working quite well (e.g. https://social.meissa-gmbh.de/@mastodonbot/104410813907729810).

**Comment by jerger** [comment]
fixed second issue - should work without expressing `:target :max-post-length`

**Comment by Manav16** [comment]
@jerger Thanks! Just went through it, the rss part is working now. Just wanted to know, am I doing the config.edn wrong because how do I make it so it mirrors suppose the "WIRED" account on twitter to the given mastodon account. Am I missing something? 

By the way, now npm start too seems to work, so I can run it using shadow-cljs release app and then node mastodon-bot.js config.edn or do npm start

**Comment by yogthos** [comment]
I think once we get the issues resolved we should publish the compiled js file in the repo for now so that users don't have to install shadow-cljs, and long term we should figure out how to publish it to NPM. Ideal workflow will be to run `npm install mastodon-bot`, and then run it with `mastodon-bot`. Need to do a bit of research to see how to publish something executable to NPM though. :)

**Comment by jerger** [comment]
prepared to get a ci-build :-)

**Comment by jerger** [comment]
There is a new release. Is there any question left open ?

**Comment by raboof** [comment]
I'm personally unblocked. I didn't review the README in depth to see if everything is correct now (perhaps we should have separate sections for 'running from the npmjs.com package' and 'running from source'), but I guess we can close this one and create specific issues when specific things are still unclear
