### ISSUE TITLE
allow reading credentials from a separate file

### ISSUE THREAD

**Issue by raboof** [yogthos/mastodon-bot#61]
So I can keep the rest of the bot configuration in public version control

**Comment by yogthos** [comment]
Yeah that's a good idea, an easy way to do this would be to add an optional `MASTODON_BOT_CREDENTIALS` environment variable, and then merge it into the config when it's populated.

**Comment by jerger** [comment]
like this idea ... maybe that's the point we can think again about using aero :-)

**Comment by yogthos** [comment]
I like aero, but might make the learning curve a bit steeper for non-Clojure users, I'd wait to see if we get at least one more requirement for modular config first :)
