### ISSUE TITLE
Security: Inspect dependencies for this three packages

### ISSUE THREAD

**Issue by jerger** [yogthos/mastodon-bot#64]
Three npm packages found opening shells on Linux, Windows systems

https://www.zdnet.com/article/three-npm-packages-found-opening-shells-on-linux-windows-systems/

**Comment by yogthos** [comment]
Oh yeah, I saw that. I think we're unaffected by that. GitHub does an automated security audit nowadays as well.

**Comment by jerger** [comment]
npm install says: 

```
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/local/bin/mastodon-bot -> /usr/local/lib/node_modules/mastodon-bot/mastodon-bot.js
```
request is on of our direct dependencies but also dependency of mastodon-api, twitter (last release 4 years ago) & oauth.

The up to date js-twitter lib is located here: https://github.com/HunterLarco/twitter-v2
they use node-fetch & new oauth
    "node-fetch": "2.6.1",
    "oauth-1.0a": "2.2.6", 

I propose also to use node fetch instead of request in our code & will open an issue at mastodon-api for using more up to date libs ...

**Comment by yogthos** [comment]
👍

**Comment by jerger** [comment]
```
npx howfat -r tree mastodon-bot | grep plutov-slack-client
npx howfat -r tree mastodon-bot | grep nodetest
```
proves that we're not affected :-)
