### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by glamoroussky** [yogthos/mastodon-bot#65]
Node.js 14
Ubuntu 20.04 LTS

root@bot:~# sudo npm install mastodon-bot -g
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/bin/mastodon-bot -> /usr/lib/node_modules/mastodon-bot/mastodon-bot.js

> deasync@0.1.15 install /usr/lib/node_modules/mastodon-bot/node_modules/deasync
> node ./build.js

gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/14.15.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/mastodon-bot/node_modules/deasync/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/mastodon-bot/node_modules/deasync/.node-gyp'
gyp ERR! System Linux 5.4.0-1028-oracle
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/mastodon-bot/node_modules/deasync
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
Build failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.15 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-03T11_48_12_882Z-debug.log

**Comment by yogthos** [comment]
I've bumped up deasync to 0.1.20, that might fix the issue.

**Comment by glamoroussky** [comment]
> I've bumped up deasync to 0.1.20, that might fix the issue.

Thank you so much, just so you know, the npm version still remain the same

**Comment by yogthos** [comment]
@jerger what do we do again to trigger a rebuild :)

**Comment by jerger** [comment]
uhh ... let me find it ...
@yogthos this should work https://github.com/yogthos/mastodon-bot/blob/master/RELEASING.md#stable-release-should-be-done-from-master

**Comment by yogthos** [comment]
Hmm, it builds for me locally but we get an error with [CI](https://github.com/yogthos/mastodon-bot/runs/1364722777?check_suite_focus=true), did I miss a step there? :)

**Comment by jerger** [comment]
Okay, will have a look at it

**Comment by yogthos** [comment]
thanks, maybe we could add a release script that does all the things like testing, bumping up the version, tagging, in order

**Comment by jerger** [comment]
the issue in our build script is 

```
failed to run function: shadow.cljs.build-report/-main
...
NoSuchFileException: .shadow-cljs/release-snapshots/app/latest/main.js
```

seems shadow-cljs build-report has an issue ... releases are maybe not located at snapshot?

https://github.com/yogthos/mastodon-bot/runs/1364722777?check_suite_focus=true

**Comment by yogthos** [comment]
Yeah I noticed that too, but we haven't changed anything with shadow config though, wonder why that broke all of a sudden.

**Comment by jerger** [comment]
may I fix this directly on master?

**Comment by yogthos** [comment]
yeah definitely :)

**Comment by jerger** [comment]
correlated with https://github.com/thheller/shadow-cljs/issues/475

**Comment by jerger** [comment]
@yogthos Seems I'm not allowed to push tags. Can u create 1.0.6 at origin/master ?

**Comment by yogthos** [comment]
oh sure thing, and let me update your permissions for the future

**Comment by jerger** [comment]
one more try using 1.0.8 ?

**Comment by yogthos** [comment]
ok going now, and can't see how you add access to push tags unfortunately

**Comment by yogthos** [comment]
hmm do we have to push to NPM separately, still looks like the old version there.

**Comment by jerger** [comment]
np - hopefully now fixed the last issue. Pls tag 1.0.9 if you're back

Unfortunately I know no nice way for having a smarter roundtrip on `programming ci` :-(

**Comment by jerger** [comment]
no - the last step (uploading to npm) used the wrong base dir

**Comment by yogthos** [comment]
Tried 1.0.9, but doesn't look like it made it either. Seems like it doesn't like the url is off `Not Found - PUT https://registry.npmjs.org/mastodon-bot - Not found`, looks like it should be https://www.npmjs.com/package/mastodon-bot

**Comment by jerger** [comment]
any idea how to configure your url ? As we do not configure any url outside of just using npm  ...

**Comment by jerger** [comment]
Tried: https://github.com/yogthos/mastodon-bot/commit/e4cd6f2f2f577bd894f5554a3e3692e7bf5965bc
But did not find any hint, which url exactly to take ...

**Comment by yogthos** [comment]
Hmm, it doesn't seem like it should need to go in package.json. I looked [here](https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-nodejs-packages), but don't see anything specific about the URL either.

**Comment by jerger** [comment]
Does the problem still exist?

In meantime we try out the installation process in a docker and test: https://gitlab.com/yogthos/mastodon-bot/-/merge_requests/9

We use debian buster for our tests .. but this should be comparable to ubuntu20.04 ...

**Comment by glamoroussky** [comment]
> Does the problem still exist?
> 
> In meantime we try out the installation process in a docker and test: https://gitlab.com/yogthos/mastodon-bot/-/merge_requests/9
> 
> We use debian buster for our tests .. but this should be comparable to ubuntu20.04 ...

Sorry for a very late reply, didn't get the time to try it, and now I can confirm it works! Thanks for your efforts!
