### ISSUE TITLE
switch from using raw promises and deasync to core.async promise API

### ISSUE THREAD

**Issue by yogthos** [yogthos/mastodon-bot#66]
following example [here](https://clojurescript.org/guides/promise-interop#using-promises-with-core-async)

**Comment by jerger** [comment]
absolutly yes :-)

**Comment by jerger** [comment]
core.async will not work as explained here: https://stackoverflow.com/questions/67396472/why-does-let-defined-atom-provide-a-different-result/67396870?noredirect=1#comment119932031_67396870

So we switched to intese the deasync usage.
