### ISSUE TITLE
Find better CI-automation

### ISSUE THREAD

**Issue by jerger** [yogthos/mastodon-bot#67]
I think gitlab-actions had some hard issues. Maybe can setup travis ci ?
Travis will be harder for setting up the credentials but a way smarter for automating steps.

**Comment by yogthos** [comment]
yeah I'm ok if we use travis ocircleci instead

**Comment by jerger** [comment]
> > ```
> > * #67 - Find better CI-automation
> > ```
> 
> do we have any particular problems with github actions? while it'd be nice to avoid github vendor lockin, basically all other CI providers would have the same problem, except for self-hosting - which I'm not sure is worth the hassle.

yes I agree about lockin's - but in addition github action is a bad tool (no idea how to say this political correct). There is no way to trigger a clean build based on a tag. I've discussed this already with GA-Support. So I think we can choose travis or gitlab-ci instead.

**Comment by yogthos** [comment]
Yeah, I'm ok with whichever one works and easiest to maintain. We can look at circle ci as well as an option.

**Comment by jerger** [comment]
I know travis and gitlab-ci very well, while Github Actions was an experiment. 

This time I will prefer not to be a pioneer ;-)

If you plan to mirro your repo at gitlab anyhow we can use gitlab-ci (nice build-graphs, nice UI for credentials), 
if not I can use travis (old school but proven, credentials by command line) ... what do you think?

**Comment by yogthos** [comment]
Sounds like a plan, let's try gitlab-ci first then. Seems like the cleanest option. :)

**Comment by jerger** [comment]
Cool :-)
In meantime I did some experiments to mirror mastodon-bot. It seems you've to do the work.
On my imported repo I can't assign ownership to your user nor can I request the project-transfer into your space ...

**Comment by yogthos** [comment]
oh sure, I can take a look.

**Comment by yogthos** [comment]
I'm getting 404 for the repo though https://gitlab.com/domaindrivenarchitecture/mastodon-bot is there some other permission you need to set? I got the invite email, but can't access it.

**Comment by jerger** [comment]
I've deleted https://gitlab.com/domaindrivenarchitecture/mastodon-bot because:

> On my imported repo I can't assign ownership to your user nor can I request the project-transfer into your space ...

I think, you have to import your repo by your own ... for a closer discussion or a pairing session if we should do the steps together you can reach me at michael.jerger@meissa-gmbh.de

**Comment by yogthos** [comment]
Ah gotcha, I misread it as you could add me as a user and I could set up the mirror. :) Let me get the repo cloned

**Comment by yogthos** [comment]
So looks like pull mirroring requires a paid gitlab account.

**Comment by jerger** [comment]
If configured it for a free at https://gitlab.com/domaindrivenarchitecture/dda-backup/-/settings/integrations

![image](https://user-images.githubusercontent.com/2706174/107410366-8086d900-6b0d-11eb-9b74-cc471ae9dcf6.png)

**Comment by yogthos** [comment]
ah nice :)

**Comment by jerger** [comment]
ah ... you should switch to public project-visibility. 

default for giltab-projects ist private - made the same experience with some of mine projects ;-)

**Comment by yogthos** [comment]
should be all set

**Comment by jerger** [comment]
Will test :-)

**Comment by jerger** [comment]
In settings / Repository you will find the merge feature:

![image](https://user-images.githubusercontent.com/2706174/107412894-68fd1f80-6b10-11eb-95dc-4032e63fb7af.png)

**Comment by jerger** [comment]
As soon you've enabled merging we can hope for a first green pipeline ...

**Comment by yogthos** [comment]
this should do it?
![image](https://user-images.githubusercontent.com/121208/107416402-70a5cf80-6ae2-11eb-9011-08797d625412.png)

**Comment by jerger** [comment]
sorry meant mirror instead of merge.

Do you want to have the main presence 
* at github (issues & PRs on github -> changes are mirrored -> gitlab -> ci is startet) or
* at gitlab (MR & issues will go to Gitlab -> maybe changes are mirrored -> github ?

**Comment by yogthos** [comment]
Ah I see, and I guess we could do development on gitlab mirroring to github. I've added you with full permissions to the project. Does it let you update the mirroring config?

**Comment by jerger** [comment]
Okay, did ci directly on GL-master :-)

> I've added you with full permissions to the project. Does it let you update the mirroring config?

Don't think so. Mirror is only avail for owner on gitlab side and you've to authz on github side.

If you provide your npm credentials, the gitlab-ci-build now may work :-)
I've set up as follows:
* master branch is protected - credentials will not be avail outside of master-branch.
* test runs on every commit / branch / mr
* commits on master will upload a prerelease to npm
* commits on master having tags will upload a release to npm

**Comment by yogthos** [comment]
Hmm I get 500 on gitlab when I try do do the mirror, maybe we can chat on clojurians slack to get this up and running. Probably easier than via github comments. :)

**Comment by yogthos** [comment]
and added the token/email variables for npm publishing

**Comment by jerger** [comment]
We've a green build on gitlab inclusive publishing to npm :-)

https://gitlab.com/yogthos/mastodon-bot/-/pipelines/255373999

**Comment by yogthos** [comment]
Fantastic, I'll try get mirroring sorted out.
