### ISSUE TITLE
publish releases to npmjs

### ISSUE THREAD

**Issue by raboof** [yogthos/mastodon-bot#69]
I would love it if a release with some of the more recent improvements was published to https://www.npmjs.com/package/mastodon-bot

Previously I've published releases manually from my laptop. Until we have CI set up I'm happy to do that again, but I currently can't build a working mastodon-bot from master due to #59 .

**Comment by yogthos** [comment]
@jerger any chance you might have a bit of time to look at the pipeline again? I think you were close, just ending up with trying to publish to a wrong url. I wonder if that might come from package.json maybe?

**Comment by yogthos** [comment]
Interestingly, I am able to publish locally after updating package.json after having removed publishConfig section. @raboof new version should be up on NPM now https://www.npmjs.com/package/mastodon-bot

**Comment by jerger** [comment]
@yogthos Sorry for beeing less responsive. At the moment we have to finish a backup soluution (https://github.com/DomainDrivenArchitecture/dda-backup) for a server which is already terminated. I think from mid of dec. I will be able to do the next step. In the time between feel free to do some experiments. I will try to support & answer questions :-)

**Comment by yogthos** [comment]
No worries, I've been swamped with work myself lately and haven't had a chance to look at my projects much either. I can just do manual releases in the meantime. Good luck with the backups! :)

**Comment by raboof** [comment]
> Interestingly, I am able to publish locally after updating package.json after having removed publishConfig section. @raboof new version should be up on NPM now https://www.npmjs.com/package/mastodon-bot

Unfortunately 1.10.0 doesn't appear to work for me: it showed 'No changes' when there were no changes to be made, but when I removed the latest toot (to test forwarding that tweet again) I got:

```
/nix/store/p11cj9nlbdyz8jz60pjn2xw2a85zcr01-node_mastodon-bot-1.10.0/lib/node_modules/mastodon-bot/mastodon-bot.js:1106
function wN(a,b,c,d,e){var f=null!=b&&(b.U&64||x===b.ba)?ee(eg,b):b;b=K.b(f,hD);f=K.b(f,Gr);return vN(a).fg("statuses",Mg(Cm.o(Vc([new Oa(null,1,[Ym,c],null),G(d)?new Oa(null,1,[Iz,d],null):null,G(f)?new Oa(null,1,[Zr,f],null):null,G(b)?new Oa(null,1,[hD,b],null):null])))).then(function(h){return e.a?e.a(h):e.call(null,h)})}function xN(a,b,c,d){return vN(a).fg("media",{file:b,description:c}).then(function(e){e=e.data.id;return d.a?d.a(e):d.call(null,e)})}
                                                                                                         ^

TypeError: vN(...).fg is not a function
    at wN (/nix/store/p11cj9nlbdyz8jz60pjn2xw2a85zcr01-node_mastodon-bot-1.10.0/lib/node_modules/mastodon-bot/mastodon-bot.js:1106:106)
    at yN (/nix/store/p11cj9nlbdyz8jz60pjn2xw2a85zcr01-node_mastodon-bot-1.10.0/lib/node_modules/mastodon-bot/mastodon-bot.js:1108:162)
    at zN (/nix/store/p11cj9nlbdyz8jz60pjn2xw2a85zcr01-node_mastodon-bot-1.10.0/lib/node_modules/mastodon-bot/mastodon-bot.js:1109:331)
    at /nix/store/p11cj9nlbdyz8jz60pjn2xw2a85zcr01-node_mastodon-bot-1.10.0/lib/node_modules/mastodon-bot/mastodon-bot.js:1153:140
    at Request._callback (/nix/store/p11cj9nlbdyz8jz60pjn2xw2a85zcr01-node_mastodon-bot-1.10.0/lib/node_modules/mastodon-bot/node_modules/twitter/lib/twitter.js:227:5)
    at Request.self.callback (/nix/store/p11cj9nlbdyz8jz60pjn2xw2a85zcr01-node_mastodon-bot-1.10.0/lib/node_modules/mastodon-bot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/nix/store/p11cj9nlbdyz8jz60pjn2xw2a85zcr01-node_mastodon-bot-1.10.0/lib/node_modules/mastodon-bot/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/nix/store/p11cj9nlbdyz8jz60pjn2xw2a85zcr01-node_mastodon-bot-1.10.0/lib/node_modules/mastodon-bot/node_modules/request/request.js:1083:12)
```

This looks like the optimizer making unsafe changes AFAICT (#63).

I agree it would be good to dig into what is wrong with those non-simple optimizations (they seemed to work for @jerger) but until we find time for that I think we should merge #63 so master builds work for everyone again.

**Comment by jerger** [comment]
Okay - I've reserved some time in the next view weeks for mastodon-bot :-)

What do you think if we work on
* #69 - publish releases to npmjs
* #67 - Find better CI-automation
* #64 - Security: Inspect dependencies for this three packages
* #59 - optimizations cause runtime crash
* #72 - Provide mastodon-bot as docker container
* and mainly #46 - Sync mastodon -> twitter? 

as a next step?

Anybody there willing to pair / review / help?

**Comment by raboof** [comment]
> Okay - I've reserved some time in the next view weeks for mastodon-bot :-)

Nice ;)

>     * #69 - publish releases to npmjs

I think that would be nice

>     * #67 - Find better CI-automation

do we have any particular problems with github actions? while it'd be nice to avoid github vendor lockin, basically all other CI providers would have the same problem, except for self-hosting - which I'm not sure is worth the hassle.

>     * #64 - Security: Inspect dependencies for this three packages

Can't hurt

>     * #59 - optimizations cause runtime crash

I don't think I can be of actual use there, but I'm happy to test at least ;)

>     * #72 - Provide mastodon-bot as docker container

If you don't dislike Nix then https://github.com/raboof/mastodon-bot-nix might be an interesting starting point - I used that to build Linux Container images (with embedded configuration so you can just run the image to do the twitter->mastodon sync)

>     * and mainly #46 - Sync mastodon -> twitter?

TBQH I personally don't care about this one ;)

**Comment by jerger** [comment]
moved discussion to the issues :-)

> > ```
> > * and mainly #46 - Sync mastodon -> twitter?
> > ```
> 
> TBQH I personally don't care about this one ;)

As company we offer mastodon as primary channel. 
But as many customers are using twitter we've to feed this channel also ...

**Comment by jerger** [comment]
publishing releases now is working at gitlab: https://gitlab.com/yogthos/mastodon-bot/-/pipelines/255373999
