### ISSUE TITLE
Lack of clarity on how to run the application

### ISSUE THREAD

**Issue by rosalogia** [yogthos/mastodon-bot#70]
There seems to be some lack of clarity on how exactly the application should be run. I installed it just fine on Ubuntu 20.04.1 LTS with `sudo npm install mastodon-bot -g` and created a config.edn file in a directory. Then I tried to run it with `mastodon-bot -h`. The output that follows is:

```
usage:
                  
  node target/mastodon-bot.js [-h] /path/to/config.edn 
  
  or
  
  npm start [-h] /path/to/config.edn
```

This already contradicts the README instructions. Trying the first option is futile since it seems to expect that you're in the project directory (and thus assumes you have the code locally). The second seems to assume the same thing, but even when I did clone the directory, it seems that there's no configuration for `start`? I'm not really sure how to run the bot.

I did clone the project eventually and compiled it with the command `npx shadow-cljs release app`. As I mentioned earlier, there seems to be no configuration for `start` as running `npm start` produces the following error: `npm ERR! missing script: start`. I tried `node mastodon-bot.js -h config.edn` and received the following error:
```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'mastodon-api'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /home/rosalogia/Projects/mbot/mastodon-bot/mastodon-bot.js:4861:615
    at Object.<anonymous> (/home/rosalogia/Projects/mbot/mastodon-bot/mastodon-bot.js:5275:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
```

So I'm really not sure how I'm meant to run this. Thanks in advance for your help! Really nice looking project here :smile:

**Comment by yogthos** [comment]
looks like the instructions from the `-h` doesn't quite print the right thing. You should should be able to install the bot by running `sudo npm install mastodon-bot -g`. Then you can run `mastodon-bot <path to config file>`, and that should be it.

There is no `start` config, instead there's a `bin` alias for executing the script:

```javascript
"bin": {
    "mastodon-bot": "./mastodon-bot.js"
  },
  ```
The reason your local build is failing is because you have to run `npm install` to pull the NPM modules the script depends on.

Hope that helps.

**Comment by jerger** [comment]
Cleaned up the Readme, help text: https://gitlab.com/yogthos/mastodon-bot

Created doc for howto setup development env: https://gitlab.com/yogthos/mastodon-bot/-/blob/master/doc/Developement.md
