### ISSUE TITLE
Running bot ends with no output

### ISSUE THREAD

**Issue by Casuallynoted** [yogthos/mastodon-bot#71]
I've been trying to run the bot to mirror a twitter account over to Mastodon. However, whenever I run it with the config it just ends. At first I thought maybe that was because the twitter account had not posted new content, but now that it has I'm seeing that the bot still just stops running without posting anything new.

**Comment by yogthos** [comment]
You might be running into this edge case:

the bot checks the specified Mastodon account to see the timestamp of the last post, and only posts content with later timestamps to avoid duplicate posts. On the first run the timestamp will default to current time.

**Comment by jerger** [comment]
What do you think about some kind of debug log output?

**Comment by yogthos** [comment]
Seems reasonable, or even just as regular output to explain what's happening. We could add something like `-v` for verbose.

**Comment by lordkitsuna** [comment]
a setting to let us specify what time to use on first run would be nice, with a sanity check of no more than 24 hours or something but being able to pull back to test config and make sure everything works without having to wait for new content would be nice as i am also having the issue of it just doesnt output anything. no errors etc but i am also getting no content even when i am pretty sure there should be

**Comment by jerger** [comment]
I use some print-debug functions for getting inputs for tests on several stages of transformation. 

For Development that's fine but as -v option that's not good enough. 

Maybe we should think about a good logging (on-console) concept with good log-levels. Any help is welcome :-)

**Comment by jerger** [comment]
Some nice idea for improve logging: https://markodenic.com/use-console-log-like-a-pro/

**Comment by yogthos** [comment]
oh I ran across that the other day, I never realized how much you could do with console.log :)

**Comment by jerger** [comment]
Found your tooth and made the link :-)

**Comment by jerger** [comment]
Just released 1.13.1 on https://gitlab.com/yogthos/mastodon-bot with improved output options :-)
