### ISSUE TITLE
Provide mastodon-bot as docker container

### ISSUE THREAD

**Issue by jerger** [yogthos/mastodon-bot#72]
We could provide mastodon-bot as docker container :-)
If that's okay, maybe we will provide the matching 

k8s deployment at https://github.com/DomainDrivenArchitecture ...

**Comment by jerger** [comment]
> > ```
> > * #72 - Provide mastodon-bot as docker container
> > ```
> 
> If you don't dislike Nix then https://github.com/raboof/mastodon-bot-nix might be an interesting starting point - I used that to build Linux Container images (with embedded configuration so you can just run the image to do the twitter->mastodon sync)

Source of inspiration is always useful :-)

I know nix as package manager only. Can we use nix packages as k8s containers directly?

**Comment by yogthos** [comment]
sounds like a plan to me :)

**Comment by jerger** [comment]
working on the issue here: https://gitlab.com/yogthos/mastodon-bot/-/merge_requests/9

**Comment by jerger** [comment]
works :-)
