### ISSUE TITLE
Provide schema as jar

### ISSUE THREAD

**Issue by jerger** [yogthos/mastodon-bot#74]
I would like to use the defined schema to validate inputs in https://gitlab.com/domaindrivenarchitecture/k8s-mastodon-bot

k8s-mastodon-bot creates k8s deployment.yaml - comparable to helm.

It can be used as webapp but also as compiled graalvm-binary. Therefore it would be nice to have the spec also as jar-dependency (you know, fail fast, validate early :-).

Provided a firs impression in https://gitlab.com/yogthos/mastodon-bot/-/merge_requests/7

If you like the idea I will proceed :-)

Pls. review the settings in project.clj - e.g. provide your clojars group.

**Comment by yogthos** [comment]
Since you've been doing most of the development on the project, would you be interested in taking over as the primary maintainer on it. Unfortunately, I simply haven't had much time to devote to it and I'd be glad to help out where I can going forward, but I feel like I'm a bit of a bottleneck right now. :)

**Comment by jerger** [comment]
I agree but would be happy if you will stay around. Do you have a good idea how we can do maintainer-pairing or achieve a good maintainer collaboration?

**Comment by yogthos** [comment]
I'm definitely happy to stick around, and feel free to tag me in the issues/prs you're doing where you think my input might be helpful. I'll help out where I can, just can't do a serious commitment to the project at the moment and don't want to get in the way because of that.

**Comment by jerger** [comment]
Finished work with

https://gitlab.com/yogthos/mastodon-bot/-/merge_requests/7 &
https://gitlab.com/yogthos/mastodon-bot/-/merge_requests/8

also improved release numbering for npm artifacts :-)
