### ISSUE TITLE
Bot runs forever but no content posted 

### ISSUE THREAD

**Issue by lordkitsuna** [yogthos/mastodon-bot#76]
I finally worked through all config problems and i thought got it working as it posted something! But it then didn't post anything else and more importantly never stopped running. I can't really tell what happened since it doesn't seem to have a verbose option at least not that i can find but something clearly is getting stuck after just one post. I can recreate this by just waiting for new content to pile up and try again. Same result, posts one thing then dies with the process just running forever taking cpu

**Comment by jerger** [comment]
I can confirm that error-handling is not optimal. If you've any deeper insights in how to handle "cljs - JavaScript-promise" interaction your help would be very welcome.

**Comment by jerger** [comment]
We improved error-handling and console outputs. Pls reopen if still valid.
