### ISSUE TITLE
Sync gitlab with github

### ISSUE THREAD

**Issue by jerger** [yogthos/mastodon-bot#77]
We should either sync both repos (gitlab -> github) or archive the github repo (and leave a prominent link to gitlab).

As our pipelines are running on gitlab I would prefer at least MR / PR / Development in gitlab. 

@yogthos what do you think ?

**Comment by jerger** [comment]
going to archive the github repo as soon as all issues are closed.

**Comment by yogthos** [comment]
sounds like a plan, will help avoid confusion :)
