### ISSUE TITLE
Help on create Twitter API

### ISSUE THREAD

**Issue by AnonymousWebHacker** [yogthos/mastodon-bot#79]
Any can recreate this step ?
I can't make it

* create a Twitter API key following the instructions here

**Comment by jerger** [comment]
Is this issue still valid? Anyone able to reproduce?

**Comment by AnonymousWebHacker** [comment]
Sorry, I have done everything without problems, except, being able to create a Twitter API key. I feel that it is very confusing, and more than that it is not my language

**Comment by jerger** [comment]
If you find any good documentation how to create twitter api key it would be great to link it :-)
On which step you got stuck ?

**Comment by AnonymousWebHacker** [comment]
Hahaha, I already searched and I have not found anything good.
Where do I stay?
I was reading your Reame.md from the repo, and I understood EVERYTHING, except the creation of twitter API :V

In fact, download your code, install it ..etc, I just wait for that configuration, until I find some guide for the twitter API I am without testing it hahaha

**Comment by jerger** [comment]
Sorry, didn't get the exact point which is not working for u ...

You followed twitters process for getting a o-auth1 api key?
https://developer.twitter.com/en/docs/authentication/oauth-1-0a/obtaining-user-access-tokens

Which step does not work?

**Comment by AnonymousWebHacker** [comment]
@jerger Excuse my ignorance, could you send me screenshots of the steps to follow? Enter the link that sent me and send me to another, and to another and in the end I have never been able to do it

**Comment by jerger** [comment]
Sorry, didn't get the exact point which is not working for u ...

You followed twitters process for getting a o-auth1 api key?
https://developer.twitter.com/en/docs/authentication/oauth-1-0a/obtaining-user-access-tokens

Which step does not work?
