### ISSUE TITLE
LICENSE file missing from root directory

### ISSUE THREAD

**Issue by TechnologyClassroom** [yogthos/mastodon-bot#80]
I see this project is under MIT. Adding a LICENSE file to the root directory would make this very obvious for people new to the project and show up in the `About` header on the first page view of the project.

Would you like me to make a PR to create the file?

**Comment by yogthos** [comment]
Sure, that sounds great!

**Comment by jerger** [comment]
can you inspect, whether merge with https://gitlab.com/yogthos/mastodon-bot has worked?
I think github is so outdated that we should archive this repo ...

**Comment by TechnologyClassroom** [comment]
I did not see it over there.  I can send a PR on that side if merging is too much of an issue.

**Comment by yogthos** [comment]
Oh yeah, let's archive this repo and I can add the license on gitlab.
