### ISSUE TITLE
Automatically parsing Tweets despite length limts

### ISSUE THREAD

**Issue by probgoblin** [yogthos/mastodon-bot#9]
I have set the length limit well above the 240 character limit of Twitter, but it is still parsing tweets into links above a certain threshold.

From mastodon-bot.cljs I have set:

(def max-post-length 1000)

and from individual config.edn files I have set
:max-post-length 1000

I am using this Exclusively for Mirroring twitter accounts to their mastodon counterparts but it seems anything over about two hundred characters is parsed into a link.

Any suggestions? Or can I just remove the entire trim-text section?

**Comment by yogthos** [comment]
Tweets aren't being trimmed at all at the moment since they're shorter than Mastodon limit. I just made a change to apply text trimming for tweets as well.

**Comment by daquinons** [comment]
Tweets are being trimmed by Twitter API because the tweet_mode="extended" parameter is not being used, so it gives back tweets limited to the original 140 characters. I fixed it and I can make a request when #10 is merged to avoid conflicts 😉
